apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgresql
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/instance: postgresql
    app.openshift.io/runtime: postgresql
  name: wanjaserver
data:
  database-name: d2FuamFkYg==
  database-password: d2FuamE=
  database-user: d2FuamE=
type: Opaque
