apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/instance: postgresql
    app.openshift.io/runtime: postgresql
  name: wanjaserver
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: wanjaserver
  sessionAffinity: None
  type: ClusterIP
